name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2

    - name: Install dependencies
      run: pnpm install

    - name: Check formatting
      run: pnpm lint

    - name: Build
      run: pnpm build

    - name: Run tests
      run: pnpm test
